server:
  port: 10011

spring:
    application:
        name: cloud-zuul

eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true。
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      #单机
      defaultZone: http://localhost:7001/eureka
      # 集群


zuul:
  routes:
    emp-provider:
      path: /**
      url: http://127.0.0.1
#      strip-prefix: false #是否要去掉前缀
